# clearing jobs

[fell_tree]
display_name = "Fell Tree"
target = "tree"
work = 5.0
tool = "chopping"
tool_required = true
keyword = ["strength", "lumbering"]
experience = 1
animation = "ChoppingDownTree"

[clear_bush]
display_name = "Clear Bush"
target = "bush"
work = 8.0
tool = "clearing"
keyword = "pioneer"
experience = 0.5
animation = "TillByHand"

[clear_stump]
display_name = "Clear Stump"
target = "stump"
work = 30.0
tool = "chopping"
tool_required = true
keyword = ["strength", "lumbering"]
experience = 1
animation = "HarvestingFlora"

[remove_stump]
display_name = "Remove Stump"
target = "stump"
work = 100.0
tool = "bartool"
toolToughness = -20
tool_required = true
keyword = ["strength", "lumbering"]
experience = 2
animation = "StumpRemoval"

# farming jobs

[till_field]
display_name = "Till Farm Plot"
work = 2.0
tool = "digging"
toolToughness = +5
keyword = "farmer"
experience = 0.1

[swidden_firewatch_job]
display_name = "Swidden Firewatch"

[sow_field]
display_name = "Sow Farm Plot"
work = 1.7
keyword = "farmer"
experience = 0.1

[harvest_root]
display_name = "Harvest Root Crops"
work = 2.5
keyword = "farmer"
experience = 0.1
animation = "TillByHand"
tool = "hoeing"

[weed_field]
display_name = "Weed Field"
tool = "hoeing"
keyword = ["farmer", "maintenance"]
experience = 0.1

[tidy_field_job]
display_name = "Move Items Out Of Farm Plot"

[harvest_grain]
display_name = "Harvest Grain Crops"
work = 1.1
keyword = "farmer"
tool = "sickle"
experience = 0.5
animation = "TillByHand"

[muck_field]
display_name = "Muck Field"
keyword = ["farmer"]
experience = 0.1

[turn_midden]
display_name = "Turn Midden"
keyword = ["farmer"]
experience = 0.1
tool = "midden_tool"
tool_required = true

# hauling jobs

[store_item]
display_name = "Store Item"
keyword = ["hauler"]
experience = 0.1

[bring_food_to_kitchen]
display_name = "Bring Food to Kitchen"
keyword = ["hauler"]
experience = 0.05

[bring_sacrificial_item]
display_name = "Bring Sacrifice to Bonfire"
keyword = ["hauler"]
experience = 0.05

[store_food]
display_name = "Store Food"
keyword = ["hauler"]
experience = 0.05

[store_armament]
display_name = "Store Weapon"
keyword = ["hauler"]
experience = 0.05

[store_bucket]
display_name = "Store Bucket"
keyword = ["hauler"]
experience = 0.05

[store_tool]
display_name = "Store Tool"
keyword = ["hauler"]
experience = 0.05

[store_product]
display_name = "Store Product"
keyword = ["hauler"]
experience = 0.1

[bring_material]
display_name = "Bring Crafting Materials"
keyword = ["hauler"]
experience = 0.1

[store_swidden_item]
display_name = "Move Organic Material Into Swidden"
keyword = ["hauler"]
experience = 0.05

[store_firewood]
display_name = "Store Firewood"
keyword = ["hauler"]
experience = 0.05

[bring_construction_materials]
display_name = "Bring Construction Materials"
keyword = ["hauler"]
experience = 0.1

[refill_job]
display_name = "Refill Scuttlebutt"
keyword = ["hauler"]
experience = 0.1
tool = "bucket"
tool_required = true

# maintenance jobs

[maintain_wood_structure]
display_name = "Maintain Wooden Structure"
keyword = ["builder", "maintenance"]
experience = 1

# fishing jobs

[spearfishing_job]
display_name = "Spearfishing"
work = 120
toolToughness = -10
# original failureChance = 0.55
failureChance = 0.15
tool = "spearfishingtool"
tool_required = true
keyword = "fisher"
experience = 1

# exploration jobs

[explore_ruin]
display_name = "Explore Ruin"
work = 5.0
keyword = "pioneer"
experience = 10

# digging jobs

# One iteration of the diggingJob will dig .25 units of earth.
[digging_job]
display_name = "Dig"
work = 8
toolToughness = +9
tool = "digging"
tool_required = true
keyword = "digger"
experience = 0.2

# firefighting jobs

[put_out_fire_job]
display_name = "Put Out Fire"
keyword = "firefighter"
experience = 2

# machine work
[work_machine_job]
display_name = "Work At Machine"

# misc.

[build_structure_job]
display_name = "Build"
experience = 2
keyword = "builder"

[clear_structure_area_job]
display_name = "Clear building area"

[craft_items_job]
display_name = "Craft Items"

[cook_job]
display_name = "Cook Food"
experience = 4
keyword = "cooking"

[demolish_job]
display_name = "Demolish building"

[ignite_bonfire_job]
display_name = "Ignite Bonfire"

[heat_sauna_job]
display_name = "Heat Sauna"

[leave_camp_job]
display_name = "Leave Camp"

[shaman_job]
display_name = "Shaman"

[guard_job]
display_name = "Guard"

[military_job]
display_name = "Military"

[sleep_job]
display_name = "Sleep"