[fire]
# How much time is added to a fire when its intensity is reduced by one
duration_per_intensity = 30.0
# These min/max values set the range of time to wait in-between attempting ot ignite objects that are in flames
low_intensity_ignite_time_min = 0.75
low_intensity_ignite_time_max = 1.25
high_intensity_ignite_time_min = 0.25
high_intensity_ignite_time_max = 1.5
# Chance to spawn a spark per "ignite"
spark_chance = 1.0
# Min/max speed for a newly created spark
spark_spawn_speed_min = 1.0
spark_spawn_speed_max = 5.0
# How many seconds of duration to add to a fire when it burns an unburned tile
duration_from_tile = 10.0
# Chance that a fire will ignite an object if the fire has a high enough intensity
base_ignite_chance = 0.5
# Chance that a fire will ignite a structure if the fire has a high enough intensity
structure_ignite_chance = 0.5
# Chance that a fire will ignite a goblin if the fire has a high enough intensity
goblin_ignite_chance = 0.5
# Chance that a structure fire will increase in intensity per ignite
structure_fire_intensity_increase_chance = 0.5
intensity_to_temperature = [20, 70, 100, 200, 400, 800]
# How much temperature can increase per ignite, if under the temperature set by the fire intensity
temperature_increase = 10.0
# Min/max times to apply burn effects to burning objects
next_burn_time_min = 4.0
next_burn_time_max = 8.0
# Min/max additional time to add to a fire's duration when it applies fire damage to an object
duration_per_burn_min = 10.0
duration_per_burn_max = 15.0
# Chance that a structure fire spreads to an additional tile, per burn check
structure_fire_spread_chance = 0.75
# How strong does wind affect spark velocity
spark_wind_strength = 10.0
# List of pairs of temperatures and chances for a spark to ignite a fire
# The temperature is the upper-bound. The ignite chance is selected by evaluating the pairs in order
# and choosing the chance once a temperature value is found that is higher than the tile's temperature
# [ [1, 0.01], [100, 0.025] ] means that for temperatures < 1 the chance a spark ignites is 1%,
# and for temperatures >= 1 and < 100 the chance is 2.5%
temperature_to_spark_ignite_chance = [ [1, 0.01], [100, 0.025], [200, 0.1], [400, 0.25], [+inf, 0.5] ]
# How long should a new fire last (see also `fire_duration_add_from_tile` and `fire_duration_per_burn_min/max`)
initial_duration = 10.0
# How does temperature affect fire resistance? Same format as `spark_ignite_chance_per_temperature`.
resist_modifier_per_temperature = [ [0, +1], [200, 0], [400, -1], [+inf, -2] ]
# Chance that a stockpile containing wooden items spontaneously ignites
stockpile_spontaneous_ignition_chance = 0.0

[mobs]
hauling_speed_multiplier = 0.0625
hauling_speed_multiplier_road = 0.125
hauling_speed_multiplier_snow = 0.125
time_to_lost_in_forest = 5
mob_disintegration_seconds = 240
fog_speed_multiplier = 0.5
road_speed_multiplier = 1.25
bog_speed_multiplier = 0.5
goblin_skin_colors = [
    [0.2313726, 0.4, 0.5058824],
    [0.28, 0.4, 0.075],
    [0.42, 0.22, 0.153],
    [0.455, 0.29, 0.404],
    [0.45, 0.404, 0.31],
    [0.44, 0.371, 0.208],
    [0.369, 0.3033, 0.12],
    [0.277, 0.248, 0.157],
]
goblin_hair_colors = [
    [0.415, 0.415, 0.415],
    [0.28, 0.4, 0.075],
    [0.42, 0.22, 0.153],
    [0.455, 0.29, 0.404],
    [0.2313726, 0.4, 0.5058824],
    [0.44, 0.371, 0.208],
    [0.369, 0.3033, 0.12],
    [0.277, 0.248, 0.157],
]

[fishing]
# maximum food points that can be extracted in a year without depleting the fishery
fishing_value = 100

[flora]
shade_fertility_modifier = -0.05

[tech]
research_points_per_season = 1.0

[shamanism]
vaki_per_month = 0.5

[spirits]
# base chance a spirit emerging from a tree will be on fire
fire_spirit_chance = 0.0
ambient_spirit_max = 20
ambient_spirits_per_month = 5

[structures]
maintenance_item_chance = 0.25
maintenance_minor_damage = "1-3"
maintenance_major_damage = "1-5"

[sacrificial_tree]
levels = [20, 50, 100, 200, 500, 1000, 2000, 3500, 5500]
# bonus väki produced by the tree each year
level_vaki_bonus = [0, 1, 1, 2, 2, 3, 3, 4, 5]
# bonus research produced by the tree each year
level_research_bonus = [1, 1, 2, 2, 3, 3, 4, 4, 5]

[midden]
midden_seconds_per_turn = 120

[camp]
size_tiers = [
    ["clearing", 0],    # 0
    ["camp", 10],       # 1
    ["settlement", 20], # 2
    ["hamlet", 50],    # 3
    ["village", 75],    # 4
    ["town", 100],      # 5
    ["stronghold", 200],      # 6
]